apiVersion: v1
kind: Service
metadata:
  name: zakatflow-svc
  namespace: zakat-system
  labels:
    app.kubernetes.io/name: zakatflow
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zakatflow
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 5001
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
